
import pandas as pd



if __name__ == "__main__":

    df = pd.read_excel('all_data_1to50831.xlsx')

    # 把一列都为空的列删除
    # df.dropna(axis=1, how='all', inplace=True)

    # 把一列大于70%都为空的列删除
    # df.dropna(axis=1, thresh=int(df.shape[0] * 0.7), inplace=True)



    # 按照列名排序
    df.sort_index(axis=1, inplace=True)
    print(df.columns.tolist())
    t = ['ABIOTROPHIA.GRANULICATELLA.SPECIES_BLOOD.CULTURE', 'ACIDFAST.BACILLI_SPUTUM',
     'ACINETOBACTER.BAUMANNII.COMPLEX_BLOOD.CULTURE', 'ACINETOBACTER.BAUMANNII.COMPLEX_CATHETER.TIP.IV',
     'ACINETOBACTER.BAUMANNII.COMPLEX_SPUTUM', 'ACINETOBACTER.BAUMANNII_SPUTUM', 'ACINETOBACTER.SP._SPUTUM',
     'ACREMONIUM.SPECIES_SPUTUM', 'AEROCOCCUS.SPECIES_BLOOD.CULTURE', 'AEROCOCCUS.SPECIES_SWAB',
     'AEROMONAS.HYDROPHILA_BLOOD.CULTURE', 'AEROMONAS.HYDROPHILA_SPUTUM', 'AEROMONAS.HYDROPHILIA.COMPLEX_BLOOD.CULTURE',
     'AEROMONAS.SPECIES_BLOOD.CULTURE', 'AEROMONAS.SPECIES_BRONCHOALVEOLAR.LAVAGE', 'AEROMONAS.SPECIES_SPUTUM',
     'AFB.GROWN.IN.CULTURE..ADDITIONAL.INFORMATION.TO.FOLLOW_SPUTUM',
     'AFB.GROWN.IN.CULTURE..ADDITIONAL.INFORMATION.TO.FOLLOW_TISSUE', 'AMOXicillin', 'AMOXicillin.Oral.Susp',
     'AMPicillin', 'AMPicillin.Suspension', 'ANAEROBIC.GRAM.NEGATIVE.ROD.S._ABSCESS',
     'ANAEROBIC.GRAM.NEGATIVE.ROD.S._SWAB', 'ANAEROBIC.GRAM.POSITIVE.COCCUS.I._BLOOD.CULTURE',
     'ANAEROBIC.GRAM.POSITIVE.COCCUS.I._SWAB', 'ANAEROBIC.GRAM.POSITIVE.ROD.S._BLOOD.CULTURE',
     'ANAEROBIC.GRAM.POSITIVE.ROD.S._SWAB', 'ASPERGILLUS.FLAVUS_SPUTUM', 'ASPERGILLUS.FUMIGATUS_SPUTUM',
     'ASPERGILLUS.NIGER_BRONCHOALVEOLAR.LAVAGE', 'ASPERGILLUS.NIGER_FLUID.OTHER', 'ASPERGILLUS.NIGER_SPUTUM',
     'ASPERGILLUS.SPECIES_SPUTUM', 'ASPERGILLUS.VERSICOLOR.GROUP._SPUTUM', 'Amoxicillin.Clavulanate.Susp.',
     'Amoxicillin.Clavulanic.Acid', 'Ampicillin.Sulbactam', 'Azithromycin',
     'BACILLUS.SPECIES..NOT.ANTHRACIS_BLOOD.CULTURE', 'BACILLUS.SPECIES..NOT.ANTHRACIS_BRONCHIAL.WASHINGS',
     'BACILLUS.SPECIES..NOT.ANTHRACIS_SPUTUM', 'BACILLUS.SPECIES..NOT.ANTHRACIS_SWAB', 'BACILLUS.SPECIES_URINE',
     'BACTEROIDES.FRAGILIS.GROUP_ABSCESS', 'BACTEROIDES.FRAGILIS.GROUP_BILE',
     'BACTEROIDES.FRAGILIS.GROUP_BLOOD.CULTURE', 'BACTEROIDES.FRAGILIS.GROUP_FLUID.OTHER',
     'BACTEROIDES.FRAGILIS.GROUP_PERITONEAL.FLUID', 'BACTEROIDES.FRAGILIS.GROUP_SWAB',
     'BACTEROIDES.FRAGILIS.GROUP_TISSUE', 'BETA.STREPTOCOCCI..NOT.GROUP.A_BRONCHOALVEOLAR.LAVAGE',
     'BETA.STREPTOCOCCI..NOT.GROUP.A_FLUID.OTHER', 'BETA.STREPTOCOCCI..NOT.GROUP.A_SPUTUM',
     'BETA.STREPTOCOCCI..NOT.GROUP.A_SWAB', 'BETA.STREPTOCOCCUS.GROUP.A_ABSCESS',
     'BETA.STREPTOCOCCUS.GROUP.A_BLOOD.CULTURE', 'BETA.STREPTOCOCCUS.GROUP.A_FLUID.OTHER',
     'BETA.STREPTOCOCCUS.GROUP.A_FOREIGN.BODY', 'BETA.STREPTOCOCCUS.GROUP.A_JOINT.FLUID',
     'BETA.STREPTOCOCCUS.GROUP.A_SPUTUM', 'BETA.STREPTOCOCCUS.GROUP.A_SWAB',
     'BETA.STREPTOCOCCUS.GROUP.A_THROAT.FOR.STREP', 'BETA.STREPTOCOCCUS.GROUP.A_TISSUE',
     'BETA.STREPTOCOCCUS.GROUP.B_ABSCESS', 'BETA.STREPTOCOCCUS.GROUP.B_BILE',
     'BETA.STREPTOCOCCUS.GROUP.B_BLOOD.CULTURE', 'BETA.STREPTOCOCCUS.GROUP.B_EAR',
     'BETA.STREPTOCOCCUS.GROUP.B_FOOT.CULTURE', 'BETA.STREPTOCOCCUS.GROUP.B_Mini.BAL',
     'BETA.STREPTOCOCCUS.GROUP.B_SPUTUM', 'BETA.STREPTOCOCCUS.GROUP.B_SWAB', 'BETA.STREPTOCOCCUS.GROUP.B_URINE',
     'BETA.STREPTOCOCCUS.GROUP.C_BLOOD.CULTURE', 'BETA.STREPTOCOCCUS.GROUP.C_SPUTUM', 'BETA.STREPTOCOCCUS.GROUP.C_SWAB',
     'BETA.STREPTOCOCCUS.GROUP.G_BLOOD.CULTURE', 'BETA.STREPTOCOCCUS.GROUP.G_JOINT.FLUID',
     'BETA.STREPTOCOCCUS.GROUP.G_SWAB', 'BETA.STREPTOCOCCUS.GROUP.G_TISSUE', 'BETA.STREPTOCOCCUS.NOT.GROUP.A.OR.B_SWAB',
     'BETA.STREPTOCOCCUS_BLOOD.CULTURE', 'BETA.STREPTOCOCCUS_SPUTUM', 'BETA.STREPTOCOCCUS_URINE',
     'CANCELLED_BLOOD.CULTURE', 'CANDIDA..TORULOPSIS..GLABRATA_ABSCESS', 'CANDIDA..TORULOPSIS..GLABRATA_BLOOD.CULTURE',
     'CANDIDA..TORULOPSIS..GLABRATA_BRONCHOALVEOLAR.LAVAGE', 'CANDIDA..TORULOPSIS..GLABRATA_FOREIGN.BODY',
     'CANDIDA..TORULOPSIS..GLABRATA_PERITONEAL.FLUID', 'CANDIDA..TORULOPSIS..GLABRATA_SWAB',
     'CANDIDA.ALBICANS..PRESUMPTIVE.IDENTIFICATION_ABSCESS', 'CANDIDA.ALBICANS..PRESUMPTIVE.IDENTIFICATION_BILE',
     'CANDIDA.ALBICANS..PRESUMPTIVE.IDENTIFICATION_SWAB', 'CANDIDA.ALBICANS..PRESUMPTIVE.IDENTIFICATION_TISSUE',
     'CANDIDA.ALBICANS_ABSCESS', 'CANDIDA.ALBICANS_BILE', 'CANDIDA.ALBICANS_BLOOD.CULTURE',
     'CANDIDA.ALBICANS_FOREIGN.BODY', 'CANDIDA.ALBICANS_PERITONEAL.FLUID', 'CANDIDA.ALBICANS_SWAB',
     'CANDIDA.GUILLIERMONDII_PERITONEAL.FLUID', 'CANDIDA.PARAPSILOSIS_BLOOD.CULTURE',
     'CANDIDA.PARAPSILOSIS_FLUID.OTHER', 'CANDIDA.PARAPSILOSIS_URINE', 'CANDIDA.TROPICALIS_BLOOD.CULTURE',
     'CAPNOCYTOPHAGA.SPECIES_BLOOD.CULTURE', 'CITROBACTER.FREUNDII.COMPLEX_ABSCESS',
     'CITROBACTER.FREUNDII.COMPLEX_BLOOD.CULTURE', 'CITROBACTER.FREUNDII.COMPLEX_EAR',
     'CITROBACTER.FREUNDII.COMPLEX_URINE', 'CITROBACTER.KOSERI_SPUTUM', 'CITROBACTER.KOSERI_URINE',
     'CITROBACTER.SPECIES_FLUID.OTHER', 'CLADOSPORIUM.SPECIES_SPUTUM', 'CLOSTRIDIUM.DIFFICILE_STOOL',
     'CLOSTRIDIUM.PERFRINGENS_BILE', 'CLOSTRIDIUM.PERFRINGENS_SWAB',
     'CLOSTRIDIUM.SPECIES.NOT.C..PERFRINGENS.OR.C..SEPTICUM_ABSCESS',
     'CLOSTRIDIUM.SPECIES.NOT.C..PERFRINGENS.OR.C..SEPTICUM_BLOOD.CULTURE',
     'CLOSTRIDIUM.SPECIES.NOT.C..PERFRINGENS.OR.C..SEPTICUM_PERITONEAL.FLUID',
     'CLOSTRIDIUM.SPECIES.NOT.C..PERFRINGENS.OR.C..SEPTICUM_SWAB', 'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._BILE',
     'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._BLOOD.CULTURE', 'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._EAR',
     'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._FOOT.CULTURE', 'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._PLEURAL.FLUID',
     'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._SWAB', 'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._TISSUE',
     'CORYNEBACTERIUM.SPECIES..DIPHTHEROIDS._URINE', 'CORYNEBACTERIUM.STRIATUM_BLOOD.CULTURE',
     'CORYNEBCATERIUM.AMYCOLATUM_BLOOD.CULTURE', 'CefazoLIN', 'CefePIME', 'Cefpodoxime.Proxetil', 'CeftazIDIME',
     'Cephalexin', 'Cephalexin.Suspension', 'Ciprofloxacin.0.3..Ophth.Soln', 'Ciprofloxacin.HCl', 'Clarithromycin',
     'Clarithromycin..Suspension.', 'Clindamycin', 'Clindamycin.Solution', 'Coagulation.dysfunction',
     'DEMATIACEOUS.MOLD_BRONCHOALVEOLAR.LAVAGE', 'DEMATIACEOUS.MOLD_SPUTUM', 'DiCLOXacillin', 'Doxycycline.Hyclate',
     'EIKENELLA.CORRODENS_BLOOD.CULTURE', 'ENTEROBACTER.AEROGENES_BILE', 'ENTEROBACTER.AEROGENES_BLOOD.CULTURE',
     'ENTEROBACTER.AEROGENES_BRONCHOALVEOLAR.LAVAGE', 'ENTEROBACTER.AEROGENES_SPUTUM',
     'ENTEROBACTER.CLOACAE.COMPLEX_BLOOD.CULTURE', 'ENTEROBACTER.CLOACAE.COMPLEX_SPUTUM',
     'ENTEROBACTER.CLOACAE.COMPLEX_SWAB', 'ENTEROBACTER.CLOACAE.COMPLEX_URINE', 'ENTEROBACTER.CLOACAE_BILE',
     'ENTEROBACTER.CLOACAE_BLOOD.CULTURE', 'ENTEROBACTER.CLOACAE_SPUTUM', 'ENTEROBACTER.CLOACAE_URINE',
     'ENTEROBACTER.GERGOVIAE_BLOOD.CULTURE', 'ENTEROBACTER.SAKAZAKII_BILE', 'ENTEROBACTERIACEAE_BLOOD.CULTURE',
     'ENTEROCOCCUS.CASSELIFLAVUS_BLOOD.CULTURE', 'ENTEROCOCCUS.FAECALIS_BLOOD.CULTURE',
     'ENTEROCOCCUS.FAECALIS_CSF.SPINAL.FLUID', 'ENTEROCOCCUS.FAECALIS_SWAB', 'ENTEROCOCCUS.FAECIUM_BLOOD.CULTURE',
     'ENTEROCOCCUS.FAECIUM_URINE', 'ENTEROCOCCUS.SP._ABSCESS', 'ENTEROCOCCUS.SP._BILE',
     'ENTEROCOCCUS.SP._BLOOD.CULTURE', 'ENTEROCOCCUS.SP._CATHETER.TIP.IV', 'ENTEROCOCCUS.SP._FLUID.OTHER',
     'ENTEROCOCCUS.SP._PERITONEAL.FLUID', 'ENTEROCOCCUS.SP._STOOL', 'ENTEROCOCCUS.SP._SWAB', 'ENTEROCOCCUS.SP._TISSUE',
     'ENTEROCOCCUS.SP._URINE', 'ESCHERICHIA.COLI_ABSCESS', 'ESCHERICHIA.COLI_BILE', 'ESCHERICHIA.COLI_BLOOD.CULTURE',
     'ESCHERICHIA.COLI_BRONCHIAL.WASHINGS', 'ESCHERICHIA.COLI_BRONCHOALVEOLAR.LAVAGE', 'ESCHERICHIA.COLI_FLUID.OTHER',
     'ESCHERICHIA.COLI_PERITONEAL.FLUID', 'ESCHERICHIA.COLI_SPUTUM', 'ESCHERICHIA.COLI_SWAB', 'ESCHERICHIA.COLI_TISSUE',
     'ESCHERICHIA.COLI_URINE', 'ESCHERICHIA.FERGUSONII_URINE', 'Erythromycin', 'Erythromycin.0.5..Ophth.Oint',
     'Erythromycin.Ethylsuccinate', 'Erythromycin.Ethylsuccinate.Suspension', 'FEW.BLASTOCYSTIS.HOMINIS_STOOL',
     'FUSOBACTERIUM.NUCLEATUM_ABSCESS', 'FUSOBACTERIUM.NUCLEATUM_BLOOD.CULTURE', 'FUSOBACTERIUM.NUCLEATUM_SWAB',
     'FUSOBACTERIUM.SPECIES_BLOOD.CULTURE', 'FUSOBACTERIUM.SPECIES_TISSUE',
     'GAMMA.I.E..NON.HEMOLYTIC..STREPTOCOCCUS_PLEURAL.FLUID', 'GEMELLA.SPECIES_URINE',
     'GRAM.NEGATIVE.ROD..1_BLOOD.CULTURE', 'GRAM.NEGATIVE.ROD..1_SPUTUM', 'GRAM.NEGATIVE.ROD..1_URINE',
     'GRAM.NEGATIVE.ROD..2_BLOOD.CULTURE', 'GRAM.NEGATIVE.ROD..2_BRONCHOALVEOLAR.LAVAGE', 'GRAM.NEGATIVE.ROD..2_SPUTUM',
     'GRAM.NEGATIVE.ROD..2_URINE', 'GRAM.NEGATIVE.ROD..3_SPUTUM', 'GRAM.NEGATIVE.ROD..4_SPUTUM',
     'GRAM.NEGATIVE.ROD.S._BLOOD.CULTURE', 'GRAM.NEGATIVE.ROD.S._BRONCHOALVEOLAR.LAVAGE',
     'GRAM.NEGATIVE.ROD.S._FLUID.OTHER', 'GRAM.NEGATIVE.ROD.S._PERITONEAL.FLUID', 'GRAM.NEGATIVE.ROD.S._PLEURAL.FLUID',
     'GRAM.NEGATIVE.ROD.S._SPUTUM', 'GRAM.NEGATIVE.ROD.S._SWAB', 'GRAM.NEGATIVE.ROD.S._TISSUE',
     'GRAM.NEGATIVE.ROD.S._URINE', 'GRAM.POSITIVE.BACTERIA_FLUID.OTHER', 'GRAM.POSITIVE.BACTERIA_SPUTUM',
     'GRAM.POSITIVE.BACTERIA_URINE', 'GRAM.POSITIVE.COCCUS.COCCI._EAR', 'GRAM.POSITIVE.COCCUS.COCCI._FOREIGN.BODY',
     'GRAM.POSITIVE.COCCUS.COCCI._URINE', 'GRAM.POSITIVE.RODS_ABSCESS', 'GRAM.POSITIVE.RODS_BLOOD.CULTURE',
     'GRAM.POSITIVE.RODS_PERITONEAL.FLUID', 'GRAM.POSITIVE.RODS_SWAB', 'GRAM.POSITIVE.RODS_TISSUE',
     'GRAM.POSITIVE.RODS_URINE', 'GRAM.VARIABLE.RODS_BLOOD.CULTURE', 'Gentamicin.0.3..Ophth..Ointment',
     'Gentamicin.Sulf..Ophth..Soln', 'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.NEGATIVE_BLOOD.CULTURE',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.NEGATIVE_BRONCHOALVEOLAR.LAVAGE',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.NEGATIVE_Mini.BAL',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.NEGATIVE_SPUTUM',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.POSITIVE_BRONCHIAL.WASHINGS',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.POSITIVE_BRONCHOALVEOLAR.LAVAGE',
     'HAEMOPHILUS.INFLUENZAE..BETA.LACTAMASE.POSITIVE_SPUTUM', 'HAEMOPHILUS.INFLUENZAE_BLOOD.CULTURE',
     'HAEMOPHILUS.INFLUENZAE_BRONCHOALVEOLAR.LAVAGE', 'HAEMOPHILUS.INFLUENZAE_SPUTUM',
     'HAEMOPHILUS.PARAINFLUENZAE_BLOOD.CULTURE', 'HAEMOPHILUS.SPECIES.NOT.INFLUENZAE_BLOOD.CULTURE',
     'HAEMOPHILUS.SPECIES.NOT.INFLUENZAE_SPUTUM', 'HAEMOPHILUS.SPECIES.NOT.INFLUENZAE_SWAB', 'HAEMOPHILUS.SP_SPUTUM',
     'HAFNIA.ALVEI_BLOOD.CULTURE', 'HAFNIA.ALVEI_PLEURAL.FLUID', 'HAFNIA.ALVEI_SWAB', 'HAFNIA.ALVEI_URINE',
     'HERPES.SIMPLEX.VIRUS.TYPE.1_BRONCHIAL.WASHINGS', 'HERPES.SIMPLEX.VIRUS.TYPE.1_THROAT.FOR.STREP',
     'KLEBSIELLA.OXYTOCA_ABSCESS', 'KLEBSIELLA.OXYTOCA_BILE', 'KLEBSIELLA.OXYTOCA_BLOOD.CULTURE',
     'KLEBSIELLA.OXYTOCA_SPUTUM', 'KLEBSIELLA.OXYTOCA_SWAB', 'KLEBSIELLA.OXYTOCA_TISSUE', 'KLEBSIELLA.OXYTOCA_URINE',
     'KLEBSIELLA.PNEUMONIAE_ABSCESS', 'KLEBSIELLA.PNEUMONIAE_BILE', 'KLEBSIELLA.PNEUMONIAE_BLOOD.CULTURE',
     'KLEBSIELLA.PNEUMONIAE_BRONCHIAL.WASHINGS', 'KLEBSIELLA.PNEUMONIAE_BRONCHOALVEOLAR.LAVAGE',
     'KLEBSIELLA.PNEUMONIAE_Mini.BAL', 'KLEBSIELLA.PNEUMONIAE_PERITONEAL.FLUID', 'KLEBSIELLA.PNEUMONIAE_SPUTUM',
     'KLEBSIELLA.PNEUMONIAE_SWAB', 'KLEBSIELLA.PNEUMONIAE_URINE', 'LACTOBACILLUS.SPECIES_BILE',
     'LACTOBACILLUS.SPECIES_BLOOD.CULTURE', 'LACTOBACILLUS.SPECIES_URINE', 'LACTOCOCCUS.SPECIES_URINE',
     'LEGIONELLA.PNEUMOPHILA..GROUP.1_BRONCHIAL.WASHINGS', 'LEGIONELLA.PNEUMOPHILA..GROUP.1_SPUTUM',
     'LISTERIA.MONOCYTOGENES_BLOOD.CULTURE', 'Levofloxacin', 'MALASSEZIA.PACHYDERMATIS_SWAB',
     'MICROCOCCUS.STOMATOCOCCUS.SPECIES_BLOOD.CULTURE', 'MOLD_BRONCHOALVEOLAR.LAVAGE', 'MOLD_SPUTUM',
     'MORAXELLA.CATARRHALIS_ASPIRATE', 'MORAXELLA.CATARRHALIS_BRONCHIAL.WASHINGS',
     'MORAXELLA.CATARRHALIS_BRONCHOALVEOLAR.LAVAGE', 'MORAXELLA.CATARRHALIS_SPUTUM', 'MORGANELLA.MORGANII_BILE',
     'MORGANELLA.MORGANII_BLOOD.CULTURE', 'MORGANELLA.MORGANII_SPUTUM', 'MORGANELLA.MORGANII_URINE',
     'MYCOBACTERIUM.AVIUM.COMPLEX_SPUTUM', 'MYCOBACTERIUM.GORDONAE_SPUTUM',
     'MYCOBACTERIUM.TUBERCULOSIS.COMPLEX_BLOOD.CULTURE', 'MYCOBACTERIUM.TUBERCULOSIS.COMPLEX_URINE',
     'MetRONIDAZOLE..FLagyl.', 'MetRONIDAZOLE.Suspension', 'NEISSERIA.MENINGITIDIS_BRONCHOALVEOLAR.LAVAGE',
     'NEISSERIA.MENINGITIDIS_SPUTUM', 'NEISSERIA.SPECIES..NOT.GONORRHOEAE_SWAB',
     'NON.FERMENTER..NOT.PSEUDOMONAS.AERUGINOSA_BLOOD.CULTURE', 'NON.FERMENTER..NOT.PSEUDOMONAS.AERUGINOSA_SPUTUM',
     'NON.FERMENTER..NOT.PSEUDOMONAS.AERUGINOSA_SWAB', 'Nitrofurantoin..Macrodantin.',
     'Nitrofurantoin.Monohyd..MacroBID.', 'ORGANISM_URINE', 'PAECILOMYCES.SPECIES_SPUTUM',
     'PANTOEA.SPECIES_BLOOD.CULTURE', 'PANTOEA.SPECIES_FLUID.OTHER',
     'PARAINFLUENZA.VIRUS.TYPE.3_Rapid.Respiratory.Viral.Screen...Culture', 'PORPHYROMONAS.SPECIES_BLOOD.CULTURE',
     'POSITIVE.FOR.INFLUENZA.A.VIRAL.ANTIGEN_Influenza.A.B.by.DFA',
     'POSITIVE.FOR.INFLUENZA.A.VIRAL.ANTIGEN_Rapid.Respiratory.Viral.Screen...Culture',
     'POSITIVE.FOR.INFLUENZA.B.VIRAL.ANTIGEN_Influenza.A.B.by.DFA',
     'POSITIVE.FOR.METHICILLIN.RESISTANT.STAPH.AUREUS_MRSA.SCREEN',
     'POSITIVE.FOR.PARAINFLUENZA.TYPE.3_Rapid.Respiratory.Viral.Screen...Culture',
     'POSITIVE.FOR.PARAINFLUENZA.VIRUS_Rapid.Respiratory.Viral.Screen...Culture',
     'POSITIVE.FOR.PNEUMOCYSTIS.JIROVECII..CARINII._BRONCHOALVEOLAR.LAVAGE',
     'POSITIVE.FOR.PNEUMOCYSTIS.JIROVECII..CARINII._Mini.BAL', 'POSITIVE.FOR.PNEUMOCYSTIS.JIROVECII..CARINII._SPUTUM',
     'POSITIVE.FOR.RESPIRATORY.SYNCYTIAL.VIRUS..RSV._Rapid.Respiratory.Viral.Screen...Culture',
     'PRESUMPTIVE.CLOSTRIDIUM.PERFRINGENS_BLOOD.CULTURE', 'PRESUMPTIVE.CLOSTRIDIUM.SEPTICUM_BLOOD.CULTURE',
     'PRESUMPTIVE.GARDNERELLA.VAGINALIS_URINE', 'PRESUMPTIVE.PEPTOSTREPTOCOCCUS.SPECIES_BLOOD.CULTURE',
     'PRESUMPTIVE.PEPTOSTREPTOCOCCUS.SPECIES_TISSUE', 'PRESUMPTIVE.PROPIONIBACTERIUM.ACNES_BLOOD.CULTURE',
     'PRESUMPTIVE.STREPTOCOCCUS.BOVIS_BILE', 'PRESUMPTIVE.STREPTOCOCCUS.BOVIS_BLOOD.CULTURE',
     'PRESUMPTIVE.STREPTOCOCCUS.BOVIS_URINE', 'PRESUMPTIVE.VEILLONELLA.SPECIES_BLOOD.CULTURE',
     'PREVOTELLA.SPECIES_BILE', 'PREVOTELLA.SPECIES_BLOOD.CULTURE', 'PREVOTELLA.SPECIES_SWAB',
     'PREVOTELLA.SPECIES_TISSUE', 'PROBABLE.ENTEROCOCCUS_FLUID.OTHER', 'PROBABLE.ENTEROCOCCUS_PERITONEAL.FLUID',
     'PROBABLE.ENTEROCOCCUS_TISSUE', 'PROBABLE.ENTEROCOCCUS_URINE', 'PROBABLE.MICROCOCCUS.SPECIES_PLEURAL.FLUID',
     'PROBABLE.MICROCOCCUS.SPECIES_SWAB', 'PROPIONIBACTERIUM.ACNES_ABSCESS', 'PROPIONIBACTERIUM.ACNES_BLOOD.CULTURE',
     'PROPIONIBACTERIUM.ACNES_SWAB', 'PROPIONIBACTERIUM.ACNES_TISSUE', 'PROTEUS.MIRABILIS_BLOOD.CULTURE',
     'PROTEUS.MIRABILIS_SPUTUM', 'PROTEUS.MIRABILIS_SWAB', 'PROTEUS.MIRABILIS_URINE', 'PROTEUS.SPECIES_SPUTUM',
     'PROTEUS.SPECIES_URINE', 'PROTEUS.VULGARIS_BLOOD.CULTURE', 'PROTEUS.VULGARIS_URINE', 'PROVIDENCIA.RETTGERI_URINE',
     'PROVIDENCIA.STUARTII_URINE', 'PSEUDOMONAS.AERUGINOSA_ABSCESS', 'PSEUDOMONAS.AERUGINOSA_BILE',
     'PSEUDOMONAS.AERUGINOSA_BLOOD.CULTURE', 'PSEUDOMONAS.AERUGINOSA_BRONCHIAL.WASHINGS',
     'PSEUDOMONAS.AERUGINOSA_BRONCHOALVEOLAR.LAVAGE', 'PSEUDOMONAS.AERUGINOSA_CATHETER.TIP.IV',
     'PSEUDOMONAS.AERUGINOSA_FOREIGN.BODY', 'PSEUDOMONAS.AERUGINOSA_PERITONEAL.FLUID', 'PSEUDOMONAS.AERUGINOSA_SPUTUM',
     'PSEUDOMONAS.AERUGINOSA_SWAB', 'PSEUDOMONAS.AERUGINOSA_URINE', 'PSEUDOMONAS.PUTIDA._BLOOD.CULTURE',
     'Penicillin.G.Benzathine', 'Penicillin.V.Potassium', 'Piperacillin.Tazobactam', 'Piperacillin.Tazobactam.Na',
     'RESEMBLING.MICROCOCCUS.STOMATOCOCCUS.SPECIES_BLOOD.CULTURE', 'Rifampin', 'SALMONELLA.ENTERITIDIS_BLOOD.CULTURE',
     'SALMONELLA.SPECIES_STOOL', 'SERRATIA.MARCESCENS_ABSCESS', 'SERRATIA.MARCESCENS_BILE',
     'SERRATIA.MARCESCENS_BLOOD.CULTURE', 'SERRATIA.MARCESCENS_BRONCHOALVEOLAR.LAVAGE',
     'SERRATIA.MARCESCENS_CATHETER.TIP.IV', 'SERRATIA.MARCESCENS_PERITONEAL.FLUID', 'SERRATIA.MARCESCENS_SPUTUM',
     'SERRATIA.MARCESCENS_SWAB', 'SERRATIA.MARCESCENS_URINE', 'SHIGELLA.FLEXNERI_BLOOD.CULTURE',
     'SHIGELLA.FLEXNERI_STOOL', 'STAPH.AUREUS.COAG.._ABSCESS', 'STAPH.AUREUS.COAG.._ASPIRATE',
     'STAPH.AUREUS.COAG.._BILE', 'STAPH.AUREUS.COAG.._BLOOD.CULTURE', 'STAPH.AUREUS.COAG.._BRONCHIAL.WASHINGS',
     'STAPH.AUREUS.COAG.._BRONCHOALVEOLAR.LAVAGE', 'STAPH.AUREUS.COAG.._CATHETER.TIP.IV', 'STAPH.AUREUS.COAG.._EAR',
     'STAPH.AUREUS.COAG.._FLUID.OTHER', 'STAPH.AUREUS.COAG.._FOOT.CULTURE', 'STAPH.AUREUS.COAG.._FOREIGN.BODY',
     'STAPH.AUREUS.COAG.._JOINT.FLUID', 'STAPH.AUREUS.COAG.._MRSA.SCREEN', 'STAPH.AUREUS.COAG.._Mini.BAL',
     'STAPH.AUREUS.COAG.._PERITONEAL.FLUID', 'STAPH.AUREUS.COAG.._PLEURAL.FLUID', 'STAPH.AUREUS.COAG.._SPUTUM',
     'STAPH.AUREUS.COAG.._SWAB', 'STAPH.AUREUS.COAG.._Staph.aureus.Screen', 'STAPH.AUREUS.COAG.._TISSUE',
     'STAPH.AUREUS.COAG.._URINE', 'STAPHYLOCOCCUS..COAGULASE.NEGATIVE..PRESUMPTIVELY.NOT.S..SAPROPHYTICUS_URINE',
     'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_BLOOD.CULTURE', 'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_CATHETER.TIP.IV',
     'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_EAR', 'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_EYE',
     'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_FOREIGN.BODY', 'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_SWAB',
     'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_TISSUE', 'STAPHYLOCOCCUS..COAGULASE.NEGATIVE_URINE',
     'STAPHYLOCOCCUS.EPIDERMIDIS_BLOOD.CULTURE', 'STAPHYLOCOCCUS.HOMINIS_BLOOD.CULTURE',
     'STAPHYLOCOCCUS.LUGDUNENSIS_URINE', 'STAPHYLOCOCCUS.SPECIES_URINE', 'STEMPHYLIUM.SP._SPUTUM',
     'STENOTROPHOMONAS..XANTHOMONAS..MALTOPHILIA_SPUTUM', 'STENOTROPHOMONAS..XANTHOMONAS..MALTOPHILIA_URINE',
     'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_ABSCESS', 'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_BLOOD.CULTURE',
     'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_CSF.SPINAL.FLUID',
     'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_PLEURAL.FLUID', 'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_SWAB',
     'STREPTOCOCCUS.ANGINOSUS..MILLERI..GROUP_TISSUE', 'STREPTOCOCCUS.ANGINOSUS_BLOOD.CULTURE',
     'STREPTOCOCCUS.BOVIS._BLOOD.CULTURE', 'STREPTOCOCCUS.INFANTARIUS.SSP..COLI..STREPTOCOCCUS.BOVIS._BLOOD.CULTURE',
     'STREPTOCOCCUS.MILLERI.GROUP_ABSCESS', 'STREPTOCOCCUS.PNEUMONIAE_ASPIRATE',
     'STREPTOCOCCUS.PNEUMONIAE_BLOOD.CULTURE', 'STREPTOCOCCUS.PNEUMONIAE_BRONCHIAL.WASHINGS',
     'STREPTOCOCCUS.PNEUMONIAE_BRONCHOALVEOLAR.LAVAGE', 'STREPTOCOCCUS.PNEUMONIAE_CSF.SPINAL.FLUID',
     'STREPTOCOCCUS.PNEUMONIAE_Mini.BAL', 'STREPTOCOCCUS.PNEUMONIAE_SPUTUM', 'STREPTOCOCCUS.SPECIES_TISSUE',
     'Silver.Sulfadiazine.1..Cream', 'SulfADIAzine', 'Sulfameth.Trimethoprim.DS', 'Sulfameth.Trimethoprim.SS',
     'Sulfameth.Trimethoprim.Suspension', 'TRICHODERMA.SP._TISSUE', 'Tobramycin.0.3..Ophth.Ointment',
     'Tobramycin.0.3..Ophth.Soln', 'Tobramycin.Dexamethasone.Ophth.Oint', 'Tobramycin.Dexamethasone.Ophth.Susp',
     'Tobramycin.Inhalation.Soln', 'Tobramycin.Sulfate', 'Trimethoprim', 'Unnamed..0', 'VIRIDANS.STREPTOCOCCI_ABSCESS',
     'VIRIDANS.STREPTOCOCCI_BILE', 'VIRIDANS.STREPTOCOCCI_BLOOD.CULTURE', 'VIRIDANS.STREPTOCOCCI_EAR',
     'VIRIDANS.STREPTOCOCCI_PERITONEAL.FLUID', 'VIRIDANS.STREPTOCOCCI_PLEURAL.FLUID', 'VIRIDANS.STREPTOCOCCI_SWAB',
     'VIRIDANS.STREPTOCOCCI_TISSUE', 'VIRIDANS.STREPTOCOCCI_URINE', 'VIRUS_BRONCHOALVEOLAR.LAVAGE', 'Vancocin',
     'Vancomycin', 'Vancomycin.25mg.mL.Ophth.Soln', 'Vancomycin.Enema', 'Vancomycin.Oral.Liquid', 'X.NF..Moxifloxacin',
     'X.NF..Moxifloxacin.0.5..Ophth', 'YEAST..PRESUMPTIVELY.NOT.C..ALBICANS_ABSCESS',
     'YEAST..PRESUMPTIVELY.NOT.C..ALBICANS_SWAB', 'YEAST_BRONCHIAL.WASHINGS', 'YEAST_BRONCHOALVEOLAR.LAVAGE',
     'YEAST_Mini.BAL', 'YEAST_PLEURAL.FLUID', 'YEAST_SPUTUM', 'YEAST_SWAB', 'YEAST_THROAT.FOR.STREP', 'YEAST_URINE',
     'aado2', 'aado2.1', 'aado2.2', 'aado2_Day2', 'aado2_Day4', 'admittime', 'age', 'age_raw', 'aids', 'aki_stage_24hr',
     'aki_stage_3day', 'aki_stage_48hr_Day2', 'aki_stage_4day_Day4', 'aki_stage_5day', 'albumin_max', 'albumin_max.1',
     'albumin_max.2', 'albumin_max_Day2', 'albumin_max_Day4', 'albumin_min', 'albumin_min.1', 'albumin_min.2',
     'albumin_min_Day2', 'albumin_min_Day4', 'alcohol_abuse', 'alp_max', 'alp_max.1', 'alp_max.2', 'alp_max_Day2',
     'alp_max_Day4', 'alp_min', 'alp_min.1', 'alp_min.2', 'alp_min_Day2', 'alp_min_Day4', 'alt_max', 'alt_max.1',
     'alt_max.2', 'alt_max_Day2', 'alt_max_Day4', 'alt_min', 'alt_min.1', 'alt_min.2', 'alt_min_Day2', 'alt_min_Day4',
     'aniongap_max', 'aniongap_max.1', 'aniongap_max.2', 'aniongap_max_Day2', 'aniongap_max_Day4', 'aniongap_min',
     'aniongap_min.1', 'aniongap_min.2', 'aniongap_min_Day2', 'aniongap_min_Day4', 'antibiotic.used_kinds_n',
     'antibiotic_group.used_kinds_n', 'antibiotic_group1', 'antibiotic_group2', 'antibiotic_group3',
     'antibiotic_group4', 'antibiotic_group5', 'antibiotic_group6', 'antibiotic_group7', 'antibiotic_group8',
     'antibiotic_group9', 'apsiii', 'apsiii_prob', 'ards_Day1', 'ards_Day2', 'ards_Day3', 'ards_Day4', 'ards_Day5',
     'ast_max', 'ast_max.1', 'ast_max.2', 'ast_max_Day2', 'ast_max_Day4', 'ast_min', 'ast_min.1', 'ast_min.2',
     'ast_min_Day2', 'ast_min_Day4', 'bac_biospec_type_counts', 'bac_org_counts', 'bands_max', 'bands_max.1',
     'bands_max.2', 'bands_max_Day2', 'bands_max_Day4', 'bands_min', 'bands_min.1', 'bands_min.2', 'bands_min_Day2',
     'bands_min_Day4', 'basic_disease_n', 'bicarbonate_max', 'bicarbonate_max.1', 'bicarbonate_max.2',
     'bicarbonate_max_Day2', 'bicarbonate_max_Day4', 'bicarbonate_min', 'bicarbonate_min.1', 'bicarbonate_min.2',
     'bicarbonate_min_Day2', 'bicarbonate_min_Day4', 'bilirubin_max', 'bilirubin_max.1', 'bilirubin_max.2',
     'bilirubin_max_Day2', 'bilirubin_max_Day4', 'bilirubin_min', 'bilirubin_min.1', 'bilirubin_min.2',
     'bilirubin_min_Day2', 'bilirubin_min_Day4', 'blood_loss_anemia', 'bmi', 'bun_max', 'bun_max.1', 'bun_max.2',
     'bun_max_Day2', 'bun_max_Day4', 'bun_min', 'bun_min.1', 'bun_min.2', 'bun_min_Day2', 'bun_min_Day4', 'calcium',
     'calcium.1', 'calcium.2', 'calcium_Day2', 'calcium_Day4', 'cardiac_arrhythmias', 'chloride_max', 'chloride_max.1',
     'chloride_max.2', 'chloride_max_Day2', 'chloride_max_Day4', 'chloride_min', 'chloride_min.1', 'chloride_min.2',
     'chloride_min_Day2', 'chloride_min_Day4', 'chol_max', 'chol_max.1', 'chol_max.2', 'chol_max_Day2', 'chol_max_Day4',
     'chol_min', 'chol_min.1', 'chol_min.2', 'chol_min_Day2', 'chol_min_Day4', 'chronic_pulmonary', 'ck_max',
     'ck_max.1', 'ck_max.2', 'ck_max_Day2', 'ck_max_Day4', 'ck_min', 'ck_min.1', 'ck_min.2', 'ck_min_Day2',
     'ck_min_Day4', 'ckmb_max', 'ckmb_max.1', 'ckmb_max.2', 'ckmb_max_Day2', 'ckmb_max_Day4', 'ckmb_min', 'ckmb_min.1',
     'ckmb_min.2', 'ckmb_min_Day2', 'ckmb_min_Day4', 'coagulopathy', 'colloid_num', 'congestive_heart_failure',
     'creatinine_max', 'creatinine_max.1', 'creatinine_max.2', 'creatinine_max_Day2', 'creatinine_max_Day4',
     'creatinine_min', 'creatinine_min.1', 'creatinine_min.2', 'creatinine_min_Day2', 'creatinine_min_Day4', 'crp_max',
     'crp_max.1', 'crp_max.2', 'crp_max_Day2', 'crp_max_Day4', 'crp_min', 'crp_min.1', 'crp_min.2', 'crp_min_Day2',
     'crp_min_Day4', 'crrt_hour', 'crrt_hour_1', 'crrt_hour_3', 'crrt_hour_5', 'crrt_num_1', 'crrt_num_10',
     'crrt_num_11', 'crrt_num_12', 'crrt_num_13', 'crrt_num_14', 'crrt_num_15', 'crrt_num_16', 'crrt_num_17',
     'crrt_num_18', 'crrt_num_19', 'crrt_num_2', 'crrt_num_20', 'crrt_num_21', 'crrt_num_22', 'crrt_num_23',
     'crrt_num_24', 'crrt_num_25', 'crrt_num_26', 'crrt_num_27', 'crrt_num_28', 'crrt_num_29', 'crrt_num_3',
     'crrt_num_30', 'crrt_num_31', 'crrt_num_32', 'crrt_num_33', 'crrt_num_34', 'crrt_num_35', 'crrt_num_36',
     'crrt_num_37', 'crrt_num_38', 'crrt_num_39', 'crrt_num_4', 'crrt_num_40', 'crrt_num_41', 'crrt_num_42',
     'crrt_num_43', 'crrt_num_5', 'crrt_num_6', 'crrt_num_7', 'crrt_num_8', 'crrt_num_9', 'crystalloid_num', 'ctni_max',
     'ctni_max.1', 'ctni_max.2', 'ctni_max_Day2', 'ctni_max_Day4', 'ctni_min', 'ctni_min.1', 'ctni_min.2',
     'ctni_min_Day2', 'ctni_min_Day4', 'db_max', 'db_max.1', 'db_max.2', 'db_max_Day2', 'db_max_Day4', 'db_min',
     'db_min.1', 'db_min.2', 'db_min_Day2', 'db_min_Day4', 'dead_180', 'dead_30', 'dead_365', 'deficiency_anemias',
     'depression', 'diabetes_complicated', 'diabetes_uncomplicated', 'diasbp_max', 'diasbp_max.1', 'diasbp_max.2',
     'diasbp_max_Day2', 'diasbp_max_Day4', 'diasbp_mean', 'diasbp_mean.1', 'diasbp_mean.2', 'diasbp_mean_Day2',
     'diasbp_mean_Day4', 'diasbp_min', 'diasbp_min.1', 'diasbp_min.2', 'diasbp_min_Day2', 'diasbp_min_Day4', 'dic_Day2',
     'dic_Day4', 'dic_day1', 'dic_day3', 'dic_day5', 'dischtime', 'dopamine_hour_Day2', 'dopamine_hour_Day4',
     'drug_abuse', 'expire_flag', 'fio2', 'fio2.1', 'fio2.2', 'fio2_Day2', 'fio2_Day4', 'fluid_electrolyte', 'gcseyes',
     'gcsmotor', 'gcsverbal', 'gender', 'ggt_max', 'ggt_max.1', 'ggt_max.2', 'ggt_max_Day2', 'ggt_max_Day4', 'ggt_min',
     'ggt_min.1', 'ggt_min.2', 'ggt_min_Day2', 'ggt_min_Day4', 'glu_dose1', 'glu_dose1_hydrocortisone',
     'glu_dose1_meprednisone', 'glu_dose2_hydrocortisone', 'glu_dose2_meprednisone', 'glu_dose3',
     'glu_dose3_hydrocortisone', 'glu_dose3_meprednisone', 'glu_dose4_hydrocortisone', 'glu_dose4_meprednisone',
     'glu_dose5', 'glu_dose5_hydrocortisone', 'glu_dose5_meprednisone', 'glucocorticoid_num_1', 'glucocorticoid_num_10',
     'glucocorticoid_num_11', 'glucocorticoid_num_12', 'glucocorticoid_num_13', 'glucocorticoid_num_14',
     'glucocorticoid_num_15', 'glucocorticoid_num_16', 'glucocorticoid_num_17', 'glucocorticoid_num_2',
     'glucocorticoid_num_3', 'glucocorticoid_num_4', 'glucocorticoid_num_5', 'glucocorticoid_num_6',
     'glucocorticoid_num_7', 'glucocorticoid_num_8', 'glucocorticoid_num_9', 'glucocorticoid_unit_1',
     'glucocorticoid_unit_10', 'glucocorticoid_unit_11', 'glucocorticoid_unit_12', 'glucocorticoid_unit_13',
     'glucocorticoid_unit_14', 'glucocorticoid_unit_15', 'glucocorticoid_unit_16', 'glucocorticoid_unit_17',
     'glucocorticoid_unit_2', 'glucocorticoid_unit_3', 'glucocorticoid_unit_4', 'glucocorticoid_unit_5',
     'glucocorticoid_unit_6', 'glucocorticoid_unit_7', 'glucocorticoid_unit_8', 'glucocorticoid_unit_9', 'glucose_max',
     'glucose_max.1', 'glucose_max.2', 'glucose_max.3', 'glucose_max.4', 'glucose_max_Day2', 'glucose_max_Day2.1',
     'glucose_max_Day4', 'glucose_max_Day4.1', 'glucose_mean', 'glucose_mean.1', 'glucose_mean_Day2',
     'glucose_mean_Day4', 'glucose_min', 'glucose_min.1', 'glucose_min.2', 'glucose_min.3', 'glucose_min.4',
     'glucose_min_Day2', 'glucose_min_Day2.1', 'glucose_min_Day4', 'glucose_min_Day4.1', 'hdl_max', 'hdl_max.1',
     'hdl_max.2', 'hdl_max_Day2', 'hdl_max_Day4', 'hdl_min', 'hdl_min.1', 'hdl_min.2', 'hdl_min_Day2', 'hdl_min_Day4',
     'heartrate_max', 'heartrate_max.1', 'heartrate_max.2', 'heartrate_max_Day2', 'heartrate_max_Day4',
     'heartrate_mean', 'heartrate_mean.1', 'heartrate_mean.2', 'heartrate_mean_Day2', 'heartrate_mean_Day4',
     'heartrate_min', 'heartrate_min.1', 'heartrate_min.2', 'heartrate_min_Day2', 'heartrate_min_Day4', 'height',
     'hematocrit_max', 'hematocrit_max.1', 'hematocrit_max.2', 'hematocrit_max_Day2', 'hematocrit_max_Day4',
     'hematocrit_min', 'hematocrit_min.1', 'hematocrit_min.2', 'hematocrit_min_Day2', 'hematocrit_min_Day4',
     'hemoglobin_max', 'hemoglobin_max.1', 'hemoglobin_max.2', 'hemoglobin_max_Day2', 'hemoglobin_max_Day4',
     'hemoglobin_min', 'hemoglobin_min.1', 'hemoglobin_min.2', 'hemoglobin_min_Day2', 'hemoglobin_min_Day4',
     'hld_dr_max', 'hld_dr_max.1', 'hld_dr_max.2', 'hld_dr_max_Day2', 'hld_dr_max_Day4', 'hld_dr_min', 'hld_dr_min.1',
     'hld_dr_min.2', 'hld_dr_min_Day2', 'hld_dr_min_Day4', 'hospital_expire_flag', 'hypertension', 'hypothyroidism',
     'icustay_id', 'input_3day_total', 'input_day1', 'input_day2', 'input_day3', 'inr_max', 'inr_max.1', 'inr_max.2',
     'inr_max_Day2', 'inr_max_Day4', 'inr_min', 'inr_min.1', 'inr_min.2', 'inr_min_Day2', 'inr_min_Day4', 'intime',
     'key_disease_group.diabete', 'key_disease_group.heat', 'key_disease_group.liver_disease', 'key_disease_group.lung',
     'key_disease_group.other', 'key_disease_group.renal_failure', 'key_disease_group.tumor', 'key_disease_n',
     'label_inr', 'label_inr_3', 'label_inr_5', 'label_inr_Day2', 'label_inr_Day4', 'label_platelet',
     'label_platelet_3', 'label_platelet_5', 'label_platelet_Day2', 'label_platelet_Day4', 'lactate_max',
     'lactate_max.1', 'lactate_max.2', 'lactate_max_Day2', 'lactate_max_Day4', 'lactate_min', 'lactate_min.1',
     'lactate_min.2', 'lactate_min_Day2', 'lactate_min_Day4', 'ldh_max', 'ldh_max.1', 'ldh_max.2', 'ldh_max_Day2',
     'ldh_max_Day4', 'ldh_min', 'ldh_min.1', 'ldh_min.2', 'ldh_min_Day2', 'ldh_min_Day4', 'ldl_max', 'ldl_max.1',
     'ldl_max.2', 'ldl_max_Day2', 'ldl_max_Day4', 'ldl_min', 'ldl_min.1', 'ldl_min.2', 'ldl_min_Day2', 'ldl_min_Day4',
     'liver_disease', 'liver_injury_Day2', 'liver_injury_Day4', 'liver_injury_day1', 'liver_injury_day3',
     'liver_injury_day5', 'lods', 'los_hospital', 'los_icu', 'lvef', 'lymphoma', 'mb1_unit', 'mb2_unit', 'mb3_unit',
     'mb4_unit', 'mb5_unit', 'mb_dose1', 'mb_dose3', 'mb_dose5', 'mb_num1', 'mb_num2', 'mb_num3', 'mb_num4', 'mb_num5',
     'meanbp_max', 'meanbp_max.1', 'meanbp_max.2', 'meanbp_max_Day2', 'meanbp_max_Day4', 'meanbp_mean', 'meanbp_mean.1',
     'meanbp_mean.2', 'meanbp_mean_Day2', 'meanbp_mean_Day4', 'meanbp_min', 'meanbp_min.1', 'meanbp_min.2',
     'meanbp_min_Day2', 'meanbp_min_Day4', 'metastatic_cancer', 'mingcs', 'myoglobin_max', 'myoglobin_max.1',
     'myoglobin_max.2', 'myoglobin_max_Day2', 'myoglobin_max_Day4', 'myoglobin_min', 'myoglobin_min.1',
     'myoglobin_min.2', 'myoglobin_min_Day2', 'myoglobin_min_Day4', 'norepinephrine_hour_Day2',
     'norepinephrine_hour_Day4', 'ntprobnp_max', 'ntprobnp_max.1', 'ntprobnp_max.2', 'ntprobnp_max_Day2',
     'ntprobnp_max_Day4', 'ntprobnp_min', 'ntprobnp_min.1', 'ntprobnp_min.2', 'ntprobnp_min_Day2', 'ntprobnp_min_Day4',
     'obesity', 'other_neurological', 'out_3day_total', 'out_day1', 'out_day2', 'out_day3', 'outtime', 'pao2fio2',
     'pao2fio2.1', 'pao2fio2.2', 'pao2fio2_Day2', 'pao2fio2_Day4', 'paralysis', 'pco2', 'pco2.1', 'pco2.2', 'pco2_Day2',
     'pco2_Day4', 'peptic_ulcer', 'peripheral_vascular', 'ph', 'ph.1', 'ph.2', 'ph_Day2', 'ph_Day4', 'platelet_max',
     'platelet_max.1', 'platelet_max.2', 'platelet_max_Day2', 'platelet_max_Day4', 'platelet_min', 'platelet_min.1',
     'platelet_min.2', 'platelet_min_Day2', 'platelet_min_Day4', 'po2', 'po2.1', 'po2.2', 'po2_Day2', 'po2_Day4',
     'potassium_max', 'potassium_max.1', 'potassium_max.2', 'potassium_max_Day2', 'potassium_max_Day4', 'potassium_min',
     'potassium_min.1', 'potassium_min.2', 'potassium_min_Day2', 'potassium_min_Day4', 'psychoses', 'pt_max',
     'pt_max.1', 'pt_max.2', 'pt_max_Day2', 'pt_max_Day4', 'pt_min', 'pt_min.1', 'pt_min.2', 'pt_min_Day2',
     'pt_min_Day4', 'ptt_max', 'ptt_max.1', 'ptt_max.2', 'ptt_max_Day2', 'ptt_max_Day4', 'ptt_min', 'ptt_min.1',
     'ptt_min.2', 'ptt_min_Day2', 'ptt_min_Day4', 'pulmonary_circulation', 'qsofa', 'renal_failure', 'resprate_max',
     'resprate_max.1', 'resprate_max.2', 'resprate_max_Day2', 'resprate_max_Day4', 'resprate_mean', 'resprate_mean.1',
     'resprate_mean.2', 'resprate_mean_Day2', 'resprate_mean_Day4', 'resprate_min', 'resprate_min.1', 'resprate_min.2',
     'resprate_min_Day2', 'resprate_min_Day4', 'rheumatoid_arthritis', 'shock1', 'shock3', 'shock5', 'shock_Day2',
     'shock_Day4', 'sirs', 'so2', 'so2.1', 'so2.2', 'so2_Day2', 'so2_Day4', 'sodium_max', 'sodium_max.1',
     'sodium_max.2', 'sodium_max_Day2', 'sodium_max_Day4', 'sodium_min', 'sodium_min.1', 'sodium_min.2',
     'sodium_min_Day2', 'sodium_min_Day4', 'sofa', 'solid_tumor', 'spo2', 'spo2.1', 'spo2.2', 'spo2_Day2', 'spo2_Day4',
     'spo2_max', 'spo2_max.1', 'spo2_max.2', 'spo2_max_Day2', 'spo2_max_Day4', 'spo2_mean', 'spo2_mean.1',
     'spo2_mean.2', 'spo2_mean_Day2', 'spo2_mean_Day4', 'spo2_min', 'spo2_min.1', 'spo2_min.2', 'spo2_min_Day2',
     'spo2_min_Day4', 'survival_day', 'sysbp_max', 'sysbp_max.1', 'sysbp_max.2', 'sysbp_max_Day2', 'sysbp_max_Day4',
     'sysbp_mean', 'sysbp_mean.1', 'sysbp_mean.2', 'sysbp_mean_Day2', 'sysbp_mean_Day4', 'sysbp_min', 'sysbp_min.1',
     'sysbp_min.2', 'sysbp_min_Day2', 'sysbp_min_Day4', 'tb_max', 'tb_max.1', 'tb_max.2', 'tb_max_Day2', 'tb_max_Day4',
     'tb_min', 'tb_min.1', 'tb_min.2', 'tb_min_Day2', 'tb_min_Day4', 'tempc_max', 'tempc_max.1', 'tempc_max.2',
     'tempc_max_Day2', 'tempc_max_Day4', 'tempc_mean', 'tempc_mean.1', 'tempc_mean.2', 'tempc_mean_Day2',
     'tempc_mean_Day4', 'tempc_min', 'tempc_min.1', 'tempc_min.2', 'tempc_min_Day2', 'tempc_min_Day4', 'tg_max',
     'tg_max.1', 'tg_max.2', 'tg_max_Day2', 'tg_max_Day4', 'tg_min', 'tg_min.1', 'tg_min.2', 'tg_min_Day2',
     'tg_min_Day4', 'totalco2', 'totalco2.1', 'totalco2.2', 'totalco2_Day2', 'totalco2_Day4', 'valvular_disease',
     'vaso_time1', 'vaso_time3', 'vaso_time5', 'vaso_time_total', 'vc_dose1', 'vc_dose3', 'vc_dose5', 'vc_num1',
     'vc_num2', 'vc_num3', 'vc_num4', 'vent_hour', 'vent_hour1', 'vent_hour3', 'vent_hour5', 'vent_hour_num_1',
     'vent_hour_num_10', 'vent_hour_num_11', 'vent_hour_num_12', 'vent_hour_num_13', 'vent_hour_num_14',
     'vent_hour_num_15', 'vent_hour_num_16', 'vent_hour_num_17', 'vent_hour_num_18', 'vent_hour_num_19',
     'vent_hour_num_2', 'vent_hour_num_20', 'vent_hour_num_21', 'vent_hour_num_22', 'vent_hour_num_23',
     'vent_hour_num_24', 'vent_hour_num_25', 'vent_hour_num_26', 'vent_hour_num_3', 'vent_hour_num_4',
     'vent_hour_num_5', 'vent_hour_num_6', 'vent_hour_num_7', 'vent_hour_num_8', 'vent_hour_num_9', 'wbc_max',
     'wbc_max.1', 'wbc_max.2', 'wbc_max_Day2', 'wbc_max_Day4', 'wbc_min', 'wbc_min.1', 'wbc_min.2', 'wbc_min_Day2',
     'wbc_min_Day4', 'weight', 'weight_loss']

    columns = []
    for i in df.columns.tolist():
        if i[-2:] == ".1":
            i = i[0:len(i) - 2]
            i += "_Day3"
        if i[-2:] == ".2":
            i = i[0:len(i) - 2]
            i += "_Day5"
        columns.append(i)
    # for i in columns:
    #     print(i)

    result = {}
    for i in range(len(columns) - 1):
        if columns[i] + "_Day3" == columns[i+1]:
            temp = []
            for j in range(0,5):
                temp.append(columns[i+j])
            result[columns[i]] = temp
    for key in result:
        print(result[key])

    # 把result中的value排序
    new_column_name = []
    add_column_name = ['ABIOTROPHIA.GRANULICATELLA.SPECIES_BLOOD.CULTURE', 'ACIDFAST.BACILLI_SPUTUM']
    new_column_name.extend(add_column_name)
    for key in result:
        result[key].sort()
        result[key][0] += "_Day1"
        new_column_name.extend(result[key])


    # 新建一个空的dataframe
    df_new = pd.DataFrame(columns=new_column_name)

    for value in result.values():
        for column_name in value:
            if column_name[-4:] == "Day3":
                df_new[column_name] = df[column_name[:-5] + ".1"]
            elif column_name[-4:] == "Day5":
                df_new[column_name] = df[column_name[:-5] + ".2"]
            elif column_name[-4:] == "Day1":
                df_new[column_name] = df[column_name[:-5]]
            else:
                df_new[column_name] = df[column_name]
    for name in add_column_name:
        df_new[name] = df[name]
    df_new.to_excel('all_data_1to50831_new.xlsx', index=False)
